{% set version = "0.9.2" %}

package:
  name: tomlkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tomlkit/tomlkit-{{ version }}.tar.gz
  sha256: ebd982d61446af95a1e082b103e250cb9e6d152eae2581d4a07d31a70b34ab0f

build:
  number: 0
  noarch: python
  script:
    # Somehow, when pyproject.toml is present, it requires poetry on Windows.
    # However, even with that dependency satisfied, we get:
    # "tomlkit cannot depend on itself"
    - rm pyproject.toml  # [not win]
    # Causes ClobberWarnings. Remove after https://github.com/sdispater/tomlkit/issues/69
    - rm -rf tests  # [not win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing >=3.6,<4.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tomlkit

about:
  home: https://github.com/sdispater/tomlkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Style preserving TOML library

extra:
  recipe-maintainers:
    - ocefpaf
