{% set version = "0.7.1" %}

package:
  name: tomlkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tomlkit/tomlkit-{{ version }}.tar.gz
  sha256: 24d6049e0765aad9c56a30dfa60d54c69f39c142112a6c57ce8f1c285b6b9d8f
  patches:
    # Causes ClobberWarnings. Remove after https://github.com/sdispater/tomlkit/issues/69
    - 0001-remove-tests-package.patch

build:
  number: 0
  script:
    # Somehow, when pyproject.toml is present, it requires poetry on Windows.
    # However, even with that dependency satisfied, we get:
    # "tomlkit cannot depend on itself"
    - del pyproject.toml  # [win]
    - rm pyproject.toml  # [not win]
    # Causes ClobberWarnings. Remove after https://github.com/sdispater/tomlkit/issues/69
    - rd /s /q tests  # [win]
    - rm -rf tests  # [not win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - typing >=3.6,<4.0  # [py<35]
    - enum34 >=1.1,<2.0  # [py27]
    - functools32 >=3.2.3,<4.0.0  # [py27]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tomlkit

about:
  home: https://github.com/sdispater/tomlkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Style preserving TOML library

extra:
  recipe-maintainers:
    - ocefpaf
